import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Download, Eye, EyeOff, FileBarChart2, Filter, LayoutDashboard, LockKeyhole, LogOut, Map, MapPin, Menu, MoreHorizontal, Route, Search, Settings2, ShieldCheck, SlidersHorizontal, TriangleAlert, X } from 'lucide-react'
import { api, type User } from './api'
import { sampleData, type Condition, type DashboardData, type RoadSegment } from './data'

type Page = 'Overview' | 'Road network' | 'Defects' | 'Reports' | 'Settings'
const nav: { label: Page; icon: typeof Map }[] = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Road network', icon: Map }, { label: 'Defects', icon: TriangleAlert }, { label: 'Reports', icon: FileBarChart2 }, { label: 'Settings', icon: Settings2 },
]
const colors: Record<Condition, string> = { Good: '#25a980', Fair: '#e9aa48', Poor: '#ed784e', Critical: '#db5c61' }
const poly = (values: number[], w: number, h: number) => values.map((v, i) => `${(i / (values.length - 1)) * w},${h - (v - 48) / 42 * h}`).join(' ')
function Logo({ light = false }: { light?: boolean }) { return <div className={`logo ${light ? 'logo-light' : ''}`}><div className="logo-mark"><span/><span/><span/></div><div className="logo-type"><strong>definitics<span className="logo-dot">.</span></strong><small>ROAD INTELLIGENCE</small></div></div> }
function Status({ value }: { value: string }) { return <span className={`status status-${value.toLowerCase().replace(/\s/g, '-')}`}><i/>{value}</span> }
function Spark({ points, color }: { points: number[]; color: string }) { return <svg className="spark" viewBox="0 0 110 42" preserveAspectRatio="none" aria-hidden="true"><polyline points={poly(points, 110, 42)} fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg> }
function NetworkMap({ selected, onSelect }: { selected: string | null; onSelect: (id: string) => void }) {
  const routes = [
    { id: 'MH-01', d: 'M106 301 C151 281 169 238 211 238 S287 216 330 178 S397 161 460 122', condition: 'Good' as Condition },
    { id: 'MH-02', d: 'M211 238 C234 201 250 145 270 83 S322 38 353 18', condition: 'Fair' as Condition },
    { id: 'MH-03', d: 'M211 238 C261 264 298 299 340 289 S412 310 488 332', condition: 'Poor' as Condition },
    { id: 'MH-04', d: 'M106 301 C120 339 155 369 162 408 S194 440 220 463', condition: 'Good' as Condition },
    { id: 'MH-05', d: 'M330 178 C385 190 414 204 474 194 S552 206 603 215', condition: 'Critical' as Condition },
    { id: 'MH-06', d: 'M106 301 C68 273 37 268 13 246', condition: 'Fair' as Condition },
  ]
  return <div className="map-canvas">
    <svg viewBox="0 0 620 480" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Illustrative road network map with condition coded routes">
      <defs><pattern id="grid" width="36" height="36" patternUnits="userSpaceOnUse"><path d="M 36 0 L 0 0 0 36" fill="none" stroke="#e7edeb" strokeWidth="1"/></pattern></defs>
      <rect width="620" height="480" fill="#f2f6f4"/><rect width="620" height="480" fill="url(#grid)" opacity=".45"/>
      <path d="M-10 104 Q106 137 172 76 T365 73 T630 40 M-10 367 Q91 359 166 390 T395 413 T640 379 M32 -20 Q69 97 16 189 T46 500 M537 -20 Q520 81 567 136 T544 500" className="map-terrain"/>
      <path d="M-10 169 C103 175 125 153 204 171 S311 109 405 88 S523 57 630 76 M-10 415 C109 410 239 358 323 376 S530 405 630 445 M61 -10 C103 81 141 128 130 203 S158 344 202 490 M433 -10 C421 89 443 158 406 253 S414 396 442 490" className="map-street"/>
      <path d="M0 49 Q110 66 202 29 M458 477 Q486 420 620 434" stroke="#d9e9e7" strokeWidth="18" fill="none" opacity=".7"/>
      <g className="map-labels"><text x="153" y="222">PUNE</text><text x="40" y="285">LONAVALA</text><text x="378" y="140">MUMBAI–PUNE</text><text x="277" y="51">NASHIK</text><text x="477" y="316">SOLAPUR</text><text x="121" y="452">SATARA</text><text x="478" y="173">AHMEDNAGAR</text></g>
      {routes.map(route => <g key={route.id} onClick={() => onSelect(route.id)} className={`map-route ${selected && selected !== route.id ? 'dimmed' : ''}`} role="button" tabIndex={0} aria-label={`Select ${route.id}`} onKeyDown={e => { if (e.key === 'Enter') onSelect(route.id) }}><path d={route.d} stroke="white" strokeWidth="13" fill="none" strokeLinecap="round"/><path d={route.d} stroke={colors[route.condition]} strokeWidth="7" fill="none" strokeLinecap="round"/><path d={route.d} stroke="transparent" strokeWidth="28" fill="none"/></g>)}
      <circle cx="211" cy="238" r="14" fill="white" stroke="#2b9e7c" strokeWidth="4"/><circle cx="211" cy="238" r="4" fill="#2b9e7c"/>
    </svg>
    <div className="map-zoom"><button aria-label="Zoom in" onClick={e => { const svg = e.currentTarget.closest('.map-canvas')?.querySelector('svg'); svg?.classList.add('zoomed') }}>+</button><button aria-label="Zoom out" onClick={e => { const svg = e.currentTarget.closest('.map-canvas')?.querySelector('svg'); svg?.classList.remove('zoomed') }}>−</button></div>
    <div className="map-scale">0 <span/> 25 km</div>
  </div>
}
function Login({ onDemo, onLogin }: { onDemo: () => void; onLogin: (user: User) => void }) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [show, setShow] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); setBusy(true); try { onLogin(await api.login(email, password)) } catch (err) { setError(err instanceof Error ? err.message : 'Sign in failed. Please try again.') } finally { setBusy(false) } }
  return <div className="login-shell"><div className="login-story"><Logo light/><div className="story-main"><div className="eyebrow light-eyebrow"><span/> THE ENTERPRISE ROAD PLATFORM</div><h1>Every road has<br/>a story. <em>See the<br/>whole picture.</em></h1><p>Turn road condition data into clearer priorities, faster action, and better journeys.</p><div className="story-visual"><div className="story-grid"/><svg viewBox="0 0 600 310" preserveAspectRatio="none"><path d="M-20 260 C95 270 128 160 230 176 S376 226 415 98 S520 78 620 40" stroke="#b8e7d9" strokeWidth="34" fill="none" opacity=".14"/><path d="M-20 260 C95 270 128 160 230 176 S376 226 415 98 S520 78 620 40" stroke="#7be0bc" strokeWidth="4" fill="none" strokeDasharray="10 10"/><circle cx="230" cy="176" r="10" fill="#b5f8d9"/><circle cx="415" cy="98" r="10" fill="#b5f8d9"/></svg><div className="story-floating"><Activity size={17}/> Network health <strong>84.2%</strong></div></div></div><div className="story-footer">© {new Date().getFullYear()} Definitics Software Solutions Private Limited</div></div><div className="login-panel"><div className="login-mobile-brand"><Logo/></div><div className="login-box"><div className="login-icon"><LockKeyhole size={23}/></div><div className="eyebrow">WELCOME BACK</div><h2>Sign in to your workspace</h2><p className="login-sub">Access your road network insights and operations.</p><form onSubmit={submit}><label htmlFor="email">Work email</label><div className="input-wrap"><input id="email" type="email" placeholder="name@company.com" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} required/></div><label htmlFor="password">Password</label><div className="input-wrap"><input id="password" type={show ? 'text' : 'password'} placeholder="Enter your password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required/><button type="button" className="input-action" onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button login-submit" disabled={busy}>{busy ? 'Signing in…' : 'Sign in securely'} <ArrowRight size={17}/></button></form><div className="divider"><span>OR</span></div><button className="demo-button" onClick={onDemo}>Explore sample workspace <ArrowUpRight size={16}/></button><div className="secure-note"><ShieldCheck size={16}/> Secure sign in via your organization’s server</div></div><div className="login-help">Need access? <a href="mailto:contact@roadbounce.com?subject=Enterprise%20portal%20access">Contact your administrator</a></div></div></div>
}
function App() {
  const [user, setUser] = useState<User | null>(null), [demo, setDemo] = useState(false), [loading, setLoading] = useState(true), [data, setData] = useState<DashboardData>(sampleData), [error, setError] = useState('')
  const [page, setPage] = useState<Page>('Overview'), [query, setQuery] = useState(''), [region, setRegion] = useState('All regions'), [condition, setCondition] = useState('All conditions'), [selected, setSelected] = useState<string | null>(null), [menu, setMenu] = useState(false), [notice, setNotice] = useState(false)
  useEffect(() => { api.me().then(u => { setUser(u); return api.dashboard() }).then(setData).catch(() => {}).finally(() => setLoading(false)) }, [])
  const segments = useMemo(() => data.segments.filter(s => (region === 'All regions' || s.region === region) && (condition === 'All conditions' || s.condition === condition) && `${s.name} ${s.id} ${s.region}`.toLowerCase().includes(query.toLowerCase())), [data, region, condition, query])
  const active = data.segments.find(s => s.id === selected)
  const totalKm = data.segments.reduce((a, s) => a + s.lengthKm, 0)
  const conditionGradient = (['Good', 'Fair', 'Poor', 'Critical'] as Condition[]).reduce(({ stops, start }, c) => { const end = start + data.segments.filter(s => s.condition === c).reduce((a,s) => a + s.lengthKm, 0) / (totalKm || 1) * 100; return { stops: `${stops}${colors[c]} ${start}% ${end}%, `, start: end } }, { stops: '', start: 0 }).stops.slice(0,-2)
  const defects = data.defects.filter(d => `${d.type} ${d.road} ${d.id}`.toLowerCase().includes(query.toLowerCase()))
  function exportCsv() { const rows = [['ID','Road','Region','Length (km)','IRI','Condition','Defects','Surveyed'], ...segments.map(s => [s.id,s.name,s.region,s.lengthKm,s.iri,s.condition,s.defects,s.surveyed])]; const csv = rows.map(row => row.map(v => `"${String(v).replace(/"/g,'""')}"`).join(',')).join('\r\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); a.download = 'road-segments-sample.csv'; a.click(); URL.revokeObjectURL(a.href) }
  function navigate(p: Page) { setPage(p); setQuery(''); setMenu(false) }
  async function signOut() { if (!demo) await api.logout().catch(() => {}); setUser(null); setDemo(false); setData(sampleData); setPage('Overview'); setSelected(null) }
  if (loading) return <div className="loading"><Logo/><div className="loader"/></div>
  if (!user && !demo) return <Login onDemo={() => setDemo(true)} onLogin={async u => { setUser(u); try { setData(await api.dashboard()); setError('') } catch { setError('Unable to load dashboard data. Please try again later.') } }}/>
  return <div className="app-shell">
    <aside className={`sidebar ${menu ? 'open' : ''}`}><div className="sidebar-top"><Logo/><button className="mobile-close" onClick={() => setMenu(false)} aria-label="Close menu"><X size={20}/></button></div><div className="workspace-switch"><div className="workspace-avatar">D</div><div><strong>Definitics Workspace</strong><span>Enterprise portal</span></div><ChevronDown size={15}/></div><div className="nav-heading">WORKSPACE</div><nav aria-label="Main navigation">{nav.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${page === label ? 'active' : ''}`} onClick={() => navigate(label)}><Icon size={19} strokeWidth={1.9}/><span>{label}</span>{label === 'Defects' && <b>{data.defects.filter(d => d.status !== 'Resolved').length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><CircleHelp size={18}/></div><strong>Need a hand?</strong><p>Get support from the Definitics team.</p><a href="mailto:contact@roadbounce.com">Contact support <ArrowUpRight size={14}/></a></div><div className="sidebar-account"><div className="account-avatar">{demo ? 'DE' : user?.name.slice(0,2).toUpperCase()}</div><div><strong>{demo ? 'Demo Explorer' : user?.name}</strong><span>{demo ? 'Sample workspace' : user?.role}</span></div><button onClick={signOut} title="Sign out" aria-label="Sign out"><LogOut size={18}/></button></div></div></aside>
    {menu && <div className="sidebar-overlay" onClick={() => setMenu(false)}/>}
    <div className="main-shell"><header className="topbar"><div className="top-left"><button className="mobile-menu" onClick={() => setMenu(true)} aria-label="Open menu"><Menu size={21}/></button><span>Workspace</span><ChevronRight size={15}/><strong>{page}</strong></div><div className="top-actions"><span className="top-date">{new Intl.DateTimeFormat('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Asia/Kolkata' }).format(new Date())}</span><span className="top-divider"/><button className="icon-button" onClick={() => setNotice(!notice)} aria-label="Notifications"><Bell size={19}/><i/></button>{notice && <div className="notification-pop"><strong>Notifications</strong><p>No new notifications in this {demo ? 'sample workspace' : 'workspace'}.</p></div>}<div className="top-avatar">{demo ? 'DE' : user?.name.slice(0,2).toUpperCase()}</div></div></header>
    <main className="content"><div className="page-header"><div><div className="eyebrow">ROAD INTELLIGENCE PLATFORM</div><h1>{page === 'Overview' ? 'Network overview' : page}</h1><p>{page === 'Overview' ? 'A clear view of your roads, conditions, and what needs attention.' : page === 'Road network' ? 'Explore road segments and condition measurements across your network.' : page === 'Defects' ? 'Track detected issues and maintenance progress in one place.' : page === 'Reports' ? 'Understand network performance and export your segment data.' : 'Workspace configuration and integration readiness.'}</p></div><div className="header-actions"><span className="sample-pill"><span/> {demo ? 'SAMPLE DATA' : 'LIVE WORKSPACE'}</span>{page !== 'Settings' && <button className="outline-button" onClick={exportCsv}><Download size={16}/> Export CSV</button>}</div></div>
      {error && <div className="error-banner" role="alert">{error}</div>}
      {demo && <div className="demo-banner"><div><span className="banner-spark">✦</span><strong>Preview mode</strong><span>All locations and metrics below are illustrative. Connect your backend to see your actual network.</span></div><button onClick={() => { setDemo(false); setPage('Overview') }}>Sign in <ArrowRight size={15}/></button></div>}
      {page === 'Overview' && <><div className="metric-grid"><div className="metric-card"><div className="metric-top"><span>Total network</span><div className="metric-icon green"><Route size={19}/></div></div><div className="metric-value">{totalKm.toFixed(1)} <small>km</small></div><div className="metric-bottom"><span className="mini-trend positive"><ArrowUpRight size={13}/> 6.2%</span> <span>vs. last survey</span><Spark points={[51,57,54,63,58,70,69,77]} color="#55b993"/></div></div><div className="metric-card"><div className="metric-top"><span>Network in good condition</span><div className="metric-icon blue"><Activity size={19}/></div></div><div className="metric-value">{Math.round(data.segments.filter(s => s.condition === 'Good').reduce((a,s) => a+s.lengthKm,0)/totalKm*100)}<small>%</small></div><div className="metric-bottom"><span className="mini-trend positive"><ArrowUpRight size={13}/> 3.8%</span> <span>vs. last survey</span><Spark points={[52,57,55,66,61,68,72,79]} color="#65a6cb"/></div></div><div className="metric-card"><div className="metric-top"><span>Average IRI</span><div className="metric-icon purple"><SlidersHorizontal size={19}/></div></div><div className="metric-value">{(data.segments.reduce((a,s) => a+s.iri,0)/data.segments.length).toFixed(1)} <small>m/km</small></div><div className="metric-bottom"><span className="mini-trend positive"><ArrowDownRight size={13}/> 0.4</span> <span>improved this period</span><Spark points={[77,72,76,68,67,60,57,54]} color="#a994ca"/></div></div><div className="metric-card"><div className="metric-top"><span>Open defects</span><div className="metric-icon coral"><TriangleAlert size={19}/></div></div><div className="metric-value">{data.defects.filter(d => d.status !== 'Resolved').length.toString().padStart(2,'0')}</div><div className="metric-bottom"><span className="mini-trend negative"><ArrowUpRight size={13}/> 2 new</span> <span>require attention</span><Spark points={[54,56,52,61,59,72,69,80]} color="#e99b7d"/></div></div></div>
      <div className="overview-grid"><section className="panel map-panel"><div className="panel-head"><div><div className="section-kicker">GEOSPATIAL VIEW</div><h2>Network condition map</h2><p>Explore road health at a glance</p></div><button className="text-action" onClick={() => navigate('Road network')}>View network <ArrowUpRight size={16}/></button></div><div className="map-wrap"><NetworkMap selected={selected} onSelect={setSelected}/><div className="map-legend"><span><i style={{background: colors.Good}}/> Good</span><span><i style={{background: colors.Fair}}/> Fair</span><span><i style={{background: colors.Poor}}/> Poor</span><span><i style={{background: colors.Critical}}/> Critical</span></div>{active && <div className="map-selection"><button onClick={() => setSelected(null)} aria-label="Close road details"><X size={15}/></button><small>SELECTED SEGMENT</small><strong>{active.name}</strong><span><Status value={active.condition}/> · IRI {active.iri} m/km</span></div>}</div></section><section className="panel condition-panel"><div className="panel-head"><div><div className="section-kicker">DISTRIBUTION</div><h2>Road condition</h2><p>By surveyed road length</p></div><button className="plain-icon" aria-label="More information" title="Calculated from sample segments"><MoreHorizontal size={20}/></button></div><div className="donut-area"><div className="donut" style={{background: `conic-gradient(${conditionGradient})`}}><div><strong>{totalKm.toFixed(0)}</strong><span>TOTAL KM</span></div></div></div><div className="condition-list">{(['Good','Fair','Poor','Critical'] as Condition[]).map(c => { const km = data.segments.filter(s => s.condition === c).reduce((a,s) => a+s.lengthKm,0); return <div key={c}><span><i style={{background:colors[c]}}/>{c}</span><strong>{km.toFixed(1)} km <small>{Math.round(km/totalKm*100)}%</small></strong></div> })}</div></section></div>
      <div className="overview-grid lower-grid"><section className="panel trend-panel"><div className="panel-head"><div><div className="section-kicker">PERFORMANCE</div><h2>Network health trend</h2><p>Condition score over the past 12 months</p></div><span className="trend-key"><i/> Health score</span></div><div className="chart"><div className="chart-y"><span>100</span><span>80</span><span>60</span><span>40</span></div><div className="chart-plot"><div className="chart-lines"><span/><span/><span/><span/></div><svg viewBox="0 0 660 150" preserveAspectRatio="none" aria-label="Illustrative network health trend increasing from 58 to 84"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#40ad86" stopOpacity=".22"/><stop offset="1" stopColor="#40ad86" stopOpacity="0"/></linearGradient></defs><polygon points={`0,150 ${poly(data.monthly,660,150)} 660,150`} fill="url(#fill)"/><polyline points={poly(data.monthly,660,150)} fill="none" stroke="#26a57a" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><circle cx="660" cy={150-(data.monthly.at(-1)!-48)/42*150} r="5" fill="#26a57a" stroke="white" strokeWidth="3"/></svg><div className="chart-months">{'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split(' ').map(m => <span key={m}>{m}</span>)}</div></div></div></section><section className="panel priority-panel"><div className="panel-head"><div><div className="section-kicker">ACTION CENTER</div><h2>Needs attention</h2><p>Highest priority segments</p></div><button className="text-action" onClick={() => navigate('Defects')}>View all <ArrowUpRight size={16}/></button></div><div className="priority-list">{[...data.segments].sort((a,b)=>b.iri-a.iri).slice(0,3).map((s,i) => <button key={s.id} onClick={() => {setSelected(s.id); navigate('Road network')}}><span className="priority-num">0{i+1}</span><div><strong>{s.name}</strong><small>{s.region} · {s.lengthKm} km</small></div><Status value={s.condition}/><ChevronRight size={16}/></button>)}</div></section></div></>}
      {page === 'Road network' && <><div className="network-layout"><section className="panel expanded-map"><div className="panel-head"><div><div className="section-kicker">NETWORK EXPLORER</div><h2>Condition map</h2><p>Select a colored route to inspect its segment</p></div></div><div className="map-wrap"><NetworkMap selected={selected} onSelect={setSelected}/><div className="map-legend"><span><i style={{background:colors.Good}}/> Good</span><span><i style={{background:colors.Fair}}/> Fair</span><span><i style={{background:colors.Poor}}/> Poor</span><span><i style={{background:colors.Critical}}/> Critical</span></div></div></section><section className="panel detail-panel"><div className="section-kicker">SEGMENT DETAILS</div>{active ? <><div className="detail-icon"><MapPin size={24}/></div><h2>{active.name}</h2><p>{active.id} · {active.region}</p><Status value={active.condition}/><div className="detail-rows"><div><span>Length</span><strong>{active.lengthKm} km</strong></div><div><span>IRI score</span><strong>{active.iri} m/km</strong></div><div><span>Detected defects</span><strong>{active.defects}</strong></div><div><span>Last surveyed</span><strong>{active.surveyed}</strong></div></div></> : <div className="detail-empty"><MapPin size={28}/><h3>Select a road</h3><p>Choose a route on the map or a row below to view its condition details.</p></div>}</section></div><RoadTable rows={segments} query={query} setQuery={setQuery} region={region} setRegion={setRegion} condition={condition} setCondition={setCondition} onSelect={setSelected} selected={selected}/></>}
      {page === 'Defects' && <section className="panel table-panel"><div className="panel-head"><div><div className="section-kicker">MAINTENANCE QUEUE</div><h2>Detected defects</h2><p>Review issues captured across the network</p></div><span className="count-badge">{defects.length} issues</span></div><div className="table-toolbar"><div className="search-box"><Search size={17}/><input placeholder="Search defects or roads..." value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search defects"/></div></div><div className="table-scroll"><table><thead><tr><th>ISSUE</th><th>ROAD & LOCATION</th><th>SEVERITY</th><th>STATUS</th><th>REPORTED</th></tr></thead><tbody>{defects.map(d => <tr key={d.id}><td><strong>{d.type}</strong><small>{d.id}</small></td><td><strong>{d.road}</strong><small>{d.chainage}</small></td><td><Status value={d.severity}/></td><td><Status value={d.status}/></td><td>{d.reported}</td></tr>)}</tbody></table>{!defects.length && <div className="empty-table">No defects match your search.</div>}</div></section>}
      {page === 'Reports' && <><div className="report-hero"><div><div className="eyebrow light-eyebrow">NETWORK INSIGHTS</div><h2>Make every maintenance<br/>decision count.</h2><p>Survey trends and segment level data, ready for your reporting workflow.</p><button onClick={exportCsv}>Download segment data <Download size={16}/></button></div><div className="report-decoration"><FileBarChart2 size={100} strokeWidth={1}/></div></div><div className="report-cards"><div className="panel report-card"><span>01 / COVERAGE</span><Map size={28}/><h3>Road inventory</h3><p>{data.segments.length} surveyed segments · {totalKm.toFixed(1)} km mapped</p><button onClick={() => navigate('Road network')}>Explore network <ArrowRight size={16}/></button></div><div className="panel report-card"><span>02 / QUALITY</span><Activity size={28}/><h3>Condition insights</h3><p>IRI scores, condition categories, and health trends in one view.</p><button onClick={() => navigate('Overview')}>View overview <ArrowRight size={16}/></button></div><div className="panel report-card"><span>03 / RESPONSE</span><TriangleAlert size={28}/><h3>Defect register</h3><p>{data.defects.filter(d=>d.status!=='Resolved').length} issues currently require follow up.</p><button onClick={() => navigate('Defects')}>Review defects <ArrowRight size={16}/></button></div></div></>}
      {page === 'Settings' && <section className="panel settings-panel"><div className="section-kicker">WORKSPACE SETTINGS</div><h2>Integration status</h2><p>The interface is prepared for your organization’s API and authentication service.</p><div className="settings-row"><div className="settings-icon"><ShieldCheck size={20}/></div><div><strong>Authentication</strong><span>{demo ? 'Sample mode — no account is signed in' : `Signed in as ${user?.email}`}</span></div><Status value={demo ? 'Sample' : 'Connected'}/></div><div className="settings-row"><div className="settings-icon"><Activity size={20}/></div><div><strong>Road data API</strong><span>{demo ? 'Awaiting backend configuration' : 'Dashboard endpoint connected'}</span></div><Status value={demo ? 'Pending' : 'Connected'}/></div><div className="settings-note"><strong>For administrators</strong><p>Set <code>VITE_API_BASE_URL</code> and implement the endpoints documented in the repository README. Server side password hashing, session controls, authorization, and rate limiting are required before production use.</p></div></section>}
      <footer className="footer">© {new Date().getFullYear()} Definitics Software Solutions Private Limited <span>Road intelligence, made actionable.</span></footer>
    </main></div></div>
}
function RoadTable({ rows, query, setQuery, region, setRegion, condition, setCondition, onSelect, selected }: { rows: RoadSegment[]; query: string; setQuery: (v:string)=>void; region:string; setRegion:(v:string)=>void; condition:string; setCondition:(v:string)=>void; onSelect:(v:string)=>void; selected:string|null }) { return <section className="panel table-panel"><div className="panel-head"><div><div className="section-kicker">ROAD INVENTORY</div><h2>All road segments</h2><p>Browse the surveyed network</p></div><span className="count-badge">{rows.length} segments</span></div><div className="table-toolbar"><div className="search-box"><Search size={17}/><input placeholder="Search roads or segment IDs..." value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search roads"/></div><div className="filter-controls"><Filter size={17}/><select value={region} onChange={e=>setRegion(e.target.value)} aria-label="Filter region"><option>All regions</option><option>West Zone</option><option>North Zone</option><option>East Zone</option><option>South Zone</option></select><select value={condition} onChange={e=>setCondition(e.target.value)} aria-label="Filter condition"><option>All conditions</option><option>Good</option><option>Fair</option><option>Poor</option><option>Critical</option></select></div></div><div className="table-scroll"><table><thead><tr><th>ROAD SEGMENT</th><th>REGION</th><th>LENGTH</th><th>IRI</th><th>CONDITION</th><th>DEFECTS</th><th>LAST SURVEYED</th><th/></tr></thead><tbody>{rows.map(s=><tr key={s.id} className={selected === s.id ? 'selected-row' : ''} onClick={()=>onSelect(s.id)}><td><strong>{s.name}</strong><small>{s.id}</small></td><td>{s.region}</td><td>{s.lengthKm} km</td><td>{s.iri} m/km</td><td><Status value={s.condition}/></td><td>{s.defects}</td><td>{s.surveyed}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table>{!rows.length && <div className="empty-table">No road segments match these filters.</div>}</div><div className="table-footer">Showing {rows.length} of {rows.length} segments <div><button disabled aria-label="Previous page"><ChevronLeft size={16}/></button><span>1</span><button disabled aria-label="Next page"><ChevronRight size={16}/></button></div></div></section> }
export default App
